#Greatly simplified since we only need to build for libretro
#Both clang & gcc work fine - clang seems to output faster code

MESENFLAGS=

#Nintendo Switch: switch_rules points CC/CXX/AR at devkitA64, so it has to be
#included before any of the toolchain-dependent variables below are evaluated
ifeq ($(platform),libnx)
	include $(DEVKITPRO)/libnx/switch_rules
endif

CXX ?= g++
CC ?= gcc

#`c++`/`g++-14`/... all report GCC, so detect clang instead of matching on the name
USE_GCC ?= $(shell $(CXX) --version | head -1 | grep -qi clang && echo false || echo true)

DEBUG ?= 0
HAVE_LTO ?= 1
STATICLINK ?= true

LINKCHECKUNRESOLVED := -Wl,-z,defs

LINKOPTIONS :=
LIBS :=
MESENOS :=
UNAME_S := $(shell uname -s)
MACHINE := $(shell $(CXX) -dumpmachine)

#The Windows core is cross-compiled from Linux (MXE), so the target triple -
#not uname - decides whether this is a Windows build
ifeq ($(platform),libnx)
	#Nintendo Switch builds a static library that gets linked into RetroArch
	MESENOS := libnx
	STATICLIB := mesen2_libretro_libnx.a
	MESENFLAGS += -DSWITCH=1 -D__SWITCH__ -DHAVE_LIBNX -D_LARGEFILE_SOURCE
	MESENFLAGS += -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE
	MESENFLAGS += -ffunction-sections -fdata-sections -ftls-model=local-exec
	MESENFLAGS += -I$(DEVKITPRO)/libnx/include -I$(DEVKITPRO)/portlibs/switch/include
	HAVE_LTO := 0
	STATICLINK := false
	LINKCHECKUNRESOLVED :=
else ifneq ($(findstring mingw,$(MACHINE)),)
	MESENOS := windows
	SHAREDLIB := mesen2_libretro.dll
	LINKCHECKUNRESOLVED := -Wl,--no-undefined
	STATICLINK := true
	LINKOPTIONS += -static
	LIBS += -lws2_32 -liphlpapi -lole32 -loleaut32 -luuid
else ifeq ($(UNAME_S),Linux)
	MESENOS := linux
	SHAREDLIB := mesen2_libretro.so
else ifeq ($(UNAME_S),Darwin)
	MESENOS := osx
	ifeq ($(platform),ios9)
		SHAREDLIB := mesen2_libretro_ios.dylib
	else ifeq ($(platform),osx)
		MESENFLAGS += -mmacosx-version-min=10.15
		SHAREDLIB := mesen2_libretro.dylib
	else
		SHAREDLIB := mesen2_libretro.dylib
	endif
	HAVE_LTO := 0
	STATICLINK := false
	LINKCHECKUNRESOLVED :=
else ifeq ($(OS),Windows_NT)
	MESENOS := windows
	SHAREDLIB := mesen2_libretro.dll
endif

ifneq ($(filter x86_64%,$(MACHINE)),)
	MESENPLATFORM := $(MESENOS)-x64
endif
ifneq ($(filter arm64% aarch64%,$(MACHINE)),)
	MESENPLATFORM := $(MESENOS)-arm64
endif

ifeq ($(DEBUG),0)
	MESENFLAGS += -O3
	ifeq ($(HAVE_LTO),1)
		MESENFLAGS += -DHAVE_LTO
		ifneq ($(USE_GCC),true)
			MESENFLAGS += -flto=thin
		else
			MESENFLAGS += -flto=auto
		endif
	endif
else
	MESENFLAGS += -O0 -g
	# Note: if compiling with a sanitizer, you will likely need to `LD_PRELOAD` the library `libMesenCore.so` will be linked against.
	ifneq ($(SANITIZER),)
		ifeq ($(SANITIZER),address)
			# Currently, `-fsanitize=address` is not supported together with `-fsanitize=thread`
			MESENFLAGS += -fsanitize=address
		else ifeq ($(SANITIZER),thread)
			# Currently, `-fsanitize=address` is not supported together with `-fsanitize=thread`
			MESENFLAGS += -fsanitize=thread
		else
$(warning Unrecognised $$(SANITIZER) value: $(SANITIZER))
		endif
		# `-Wl,-z,defs` is incompatible with the sanitizers in a shared lib, unless the sanitizer libs are linked dynamically; hence `-shared-libsan` (not the default for Clang).
		# It seems impossible to link dynamically against two sanitizers at the same time, but that might be a Clang limitation.
		ifneq ($(USE_GCC),true)
			MESENFLAGS += -shared-libsan
		endif
	endif
endif

ifneq ($(STATICLINK),false)
	LINKOPTIONS += -static-libgcc -static-libstdc++ 
endif

CXXFLAGS = -fPIC -Wall --std=c++17 $(MESENFLAGS) -I $(realpath ./) -I $(realpath ./Core) -I $(realpath ./Utilities)
CFLAGS = -fPIC -Wall $(MESENFLAGS)

CORESRC := $(shell find Core -name '*.cpp')
COREOBJ := $(CORESRC:.cpp=.o)

UTILSRC := $(shell find Utilities -name '*.cpp' -o -name '*.c')
UTILOBJ := $(addsuffix .o,$(basename $(UTILSRC)))

SEVENZIPSRC := $(shell find SevenZip -name '*.c')
SEVENZIPOBJ := $(SEVENZIPSRC:.c=.o)

#unix.c/unixdgram.c/unixstream.c/serial.c are optional luasocket modules that
#are never registered by the core (and don't build on Windows)
LUASRC := $(filter-out Lua/unix.c Lua/unixdgram.c Lua/unixstream.c Lua/serial.c,$(shell find Lua -name '*.c'))
LUAOBJ := $(LUASRC:.c=.o)

ifeq ($(platform),unix)
LDFLAGS += -Wl,--version-script=Libretro/link.T -Wl,--no-undefined
endif

libretro: CFLAGS   += -D LIBRETRO
libretro: CXXFLAGS += -D LIBRETRO

all: libretro

ifeq ($(platform),libnx)
libretro: Libretro/libretro.o $(SEVENZIPOBJ) $(LUAOBJ) $(UTILOBJ) $(COREOBJ)
	$(AR) rcs $(STATICLIB) $^
else
libretro: Libretro/libretro.o $(SEVENZIPOBJ) $(LUAOBJ) $(UTILOBJ) $(COREOBJ)
	$(CXX) $(CXXFLAGS) $(LINKOPTIONS) $(LINKCHECKUNRESOLVED) $(LDFLAGS) -shared -o $(SHAREDLIB) Libretro/libretro.o $(SEVENZIPOBJ) $(LUAOBJ) $(UTILOBJ) $(COREOBJ) -pthread $(LIBS)
endif

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
	
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(COREOBJ)
	rm -f $(UTILOBJ)
	rm -f $(SEVENZIPOBJ)
	rm -f $(LUAOBJ)
	rm -f $(SHAREDLIB)
	rm -f $(STATICLIB)
	rm -f Libretro/libretro.o
